### ISSUE TITLE
general question about your experience building this project

### ISSUE THREAD

**Issue by ghost** [tsinis/password_manager#1]
Hi @tsinis  ,

Hope you are all well !

I would like to create a clone of [teampass](https://github.com/nilsteampassnet/TeamPass) a collaborative password manager, and I was wondering if you knew or can explain how to create a catalog of items, organised with an [animated tree view](https://github.com/embraceitmobile/animated_tree_view), and [flutter_rbac](https://github.com/wilpar/flutter_rbac) for managing roles and permissions. From your experience, what advices would you give me for neat architecture.

Thanks for any insights or inputs on that question.

teampass screeenshot:
![pf_tp_5](https://user-images.githubusercontent.com/1963546/143676762-88e5e5c0-6a3e-473f-adae-09d9ae274f18.png)

Cheers,
Luc

**Comment by tsinis** [comment]
Hey @lucmichalski,

Sorry for the late reply. I am quite surprised, this project I wrote in less than 16h, just for a job interview :). But to the point, it's quite a complicated question, considering that I don't know the size of your team, nor have experience with these two packages, etc. Nevertheless, it seems to me that protected tree-like data structures would be easiest to store in [mоor/drift](https://github.com/simolus3/moor). For DB keys, I suggest [securе storage](https://github.com/mogol/flutter_secure_storage). It's one of the best pairs of packages to tie together. I wouldn't get hung up on a particular user-interface package, but even if you want to use that Animated Tree View package, as far as I can see, you can use streams from drift and map them there. For state management, I would take [BLoC](https://github.com/felangel/bloc), it's always a good choice especially considering that Firebase is also quite declarative. Sorry for the rather abstract answer and thanks for your interest!
